### ISSUE TITLE
This fork is buggy

### ISSUE THREAD

**Issue by eugene-nuwber** [bistrosk/elasticsearch-dsl#3]
We tried to use this fork as it was mentioned in one of PR's from the original package.

Unfortunately it's buggy. Many of our tests failed.

For example: there's the line https://github.com/bistrosk/elasticsearch-dsl/blob/master/src/Aggregation/Bucketing/RangeAggregation.php#L41 which sets `key` to null and then tries to `addRange` which expects the arg `$key` to be a string.

I think nobody tried to run and fix tests here.

**Comment by C0mp4ct** [comment]
fixed in v8.0.4
